MaterialTabs equal spacing
SwiftKickMobile/SwiftUIMaterialTabs pull request #6
Opened 2024-05-01 16:33 UTC by cfoughty7

Adds a new sizing option to the `MaterialTabBar.Sizing` enum.

Equal Spacing...
- sizes tabs based on their intrinsic content size
- spaces the tabs apart by the provided sizing metric
- horizontally centers the tab bar if the total tab size is less than the available space
- scrolls the tabs horizontally if the total tab size overflows the available space

#### Smaller than available space
https://github.com/SwiftKickMobile/SwiftUIMaterialTabs/assets/43048580/c2b757f7-ba3a-46b9-a59f-6b6124d41d08

#### Larger than available space
https://github.com/SwiftKickMobile/SwiftUIMaterialTabs/assets/43048580/cf30d31c-68aa-4f5d-b8cd-2f9f159bab6a

2024-05-01 19:12 UTC, cfoughty7 commented on Sources/SwiftUIMaterialTabs/Internal/PreferenceKeys/WidthPreferenceKey.swift
This appeared to be unused.

2024-05-03 02:12 UTC, wtmoose requested changes

2024-05-03 02:12 UTC, wtmoose commented on Sources/SwiftUIMaterialTabs/MaterialTabs/MaterialTabBar.swift
> +    ///   - spacing: The amount of spacing to use between tabs.
```suggestion
    ///   - spacing: The amount of spacing to use between tabs. Primary and Secondary tabs should use the default spacing of 0 to form a continuous line across the bottom of the tab bar.
```

2024-05-03 02:12 UTC, wtmoose commented on Sources/SwiftUIMaterialTabs/MaterialTabs/MaterialTabBar.swift
> +    ///   - fillAvailableSpace: When true, tabs assume the maximum space needed to fill the screen or scroll if they overflow the available space.
```suggestion
    ///   - fillAvailableSpace: When `true`, tabs assume the maximum space needed to fill the screen or scroll if they overflow the available space.
```

2024-05-15 13:31 UTC, merged